name: nfc_app
description: A Flutter app for reading and writing NFC tags.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  flutter_nfc_kit: ^3.4.3
  ndef: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
